#iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Controllers for singular joint ------------------------------------
  # 
  # Effort Position Controllers ---------------------------------------
  iiwa_joint_1_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_1
    pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

  iiwa_joint_2_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_2
    pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

  iiwa_joint_3_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_3
    pid: {p: 800.0, i: 10, d: 5.0, i_clamp_min: -10000, i_clamp_max: 10000}

  iiwa_joint_4_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_4
    pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

  iiwa_joint_5_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_5
    pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}

  iiwa_joint_6_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_6
    pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

  iiwa_joint_7_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_7
    pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

  # Forward Position Controllers ---------------------------------------
  iiwa_joint_1_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_1


  iiwa_joint_2_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_2
    
  iiwa_joint_3_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_3
    
  iiwa_joint_4_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_4
    
  iiwa_joint_5_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_5
    
  iiwa_joint_6_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_6
    
  iiwa_joint_7_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_7
    
  # Forward Velocity Controllers ---------------------------------------
  iiwa_joint_1_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_1
    
  iiwa_joint_2_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_2
    
  iiwa_joint_3_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_3
    
  iiwa_joint_4_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_4
    
  iiwa_joint_5_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_5
    
  iiwa_joint_6_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_6
    
  iiwa_joint_7_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_7
    
    
  # Trajectory Controllers ---------------------------------------
  #   
  # Effort Position Controllers ---------------------------------------
  eff_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
    gains:
      iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30}
      iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
      iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
      iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
      iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
      iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
      iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
    
  # Forward Position Controllers ---------------------------------------
  pos_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
    
  # Forward Velocity Controllers ---------------------------------------
  vel_joint_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
    gains:
      iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30}
      iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
      iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
      iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
      iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
      iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
      iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default




