lbr_iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  lbr_iiwa_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lbr_iiwa_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lbr_iiwa_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lbr_iiwa_joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lbr_iiwa_joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_5
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lbr_iiwa_joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_6
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lbr_iiwa_joint_7_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_7
    pid: {p: 100.0, i: 0.01, d: 10.0}


